name: Stable Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq libfuse2 libpulse0

      - name: Download CraftOS-PC
        run: |
          API_URL="https://api.github.com/repos/MCJack123/craftos2/releases/latest"
          ASSET_URL=$(curl -s $API_URL \
            | jq -r '.assets[] | select(.name | test("AppImage")) | .browser_download_url')
          curl -L -o CraftOS-PC.AppImage "$ASSET_URL"
          chmod +x CraftOS-PC.AppImage
          mv CraftOS-PC.AppImage /usr/local/bin/craftos

      - name: Run build.sh
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Create archive
        run: |
          mkdir artifact
          cp build/radon.lua artifact/
          cp config.lua artifact/
          cp products.lua artifact/
          cp eventHooks.lua artifact/
          cp CardLayout.lua artifact/
          tar -cf release.tar -C artifact .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          prerelease: false
          files: |
            release.tar
            artifact/radon.lua
